### ISSUE TITLE
Xếp ghế cho lớp học

### ISSUE THREAD

**Issue by rinodung** [rinodung/mo-phong-hoc-truc-tuyen#5]
**Flash**
Dùng ChairArray lưu thứ tự ghế(0,1,2,3...) và toạ độ của ghế

**Red5 Server**
ShareObject lưu data dưới dạng mảng client, mỗi client sẽ lưu position là vị trí của ghế(0,1,2,3), mặc định người mới chưa có ghế có position = -1

*_Chú ý: *_ Position ở đây là index của mảng ChairArray chứ không lưu toạ độ ghế x,y nữa, vì có index mảng ChairArray chúng ta dễ dàng lấy được toạ độ. Nói cách khác mỗi client trên Red5 Server đều được đánh số ghế(0,1,2,3,4... 9, 10)

**Ý tưởng xếp ghế** 
1. Sự kiện Update Onlinle list Flash nhận được một mãng client(data)
2. Reset lại tất cả các ghế trống(id=0, myavatar =0, removeChild)
3. Xếp ghế cho những người có ghế (position != -1)
  **==>** Có position là index của mảng ChairArray, Duyệt vòng lặp ChairArray để cặp nhật lại avatar, id
4. Xếp ghế cho những người không có ghế(position ==-1)
**==>** Có position là index của mảng ChairArray, Duyệt vòng lặp ChairArray tìm ra ghế trống(id=0) gần nhất, cập nhật lại position lên ShareObject trên Red5 Server
Lúc này người mới vào, người thoát ra thì sự kiên Update Online List luôn luôn xảy ra, quay lại bước 1.

**Comment by dieuhien** [comment]
ok em, chị sẽ thử lại,
Thks.

_----------------------------------------------------------------------------------------------------------------_
_HUỲNH PHAN DIỆU HIỀN_
KHOA CÔNG NGHỆ THÔNG TIN - TRƯỜNG TCN Kỹ Thuật CN Hùng Vương
161 - 165 Nguyễn Chí Thanh, Phường 12, Quận 5
Phone: _090.880.6646_
Email: hphandieuhien@gmail.com
