### ISSUE TITLE
Mô phỏng trạng thái của học viên

### ISSUE THREAD

**Issue by dieuhien** [rinodung/mo-phong-hoc-truc-tuyen#8]
1. Bình thường
2. định danh(mũi tên)
3. giơ tay phát biểu
4. phát biểu
5. lắc đầu

**Comment by rinodung** [comment]
chị cập nhật trạng thái danh sách này lại giúp em nhé

**Comment by dieuhien** [comment]
1.Bình thường
2.Giơ tay
3. Phát biểu
4.Cười
5. Buồn
6. Lắc đầu qua trái
7. Lắc đầu qua phải
8. Gật đầu
9. Ngáp
10. Ngủ gật
